- hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Test_connexion 
      ping:
  
  roles:
    #- install_docker
    - create_network
    - launch_proxy
    - launch_database
    - launch_app

